#include <shl_ref.h>

int main(int argc, char **argv)
{
	struct csinn_session *sess = csinn_alloc_session();
	sess->base_run_mode = CSINN_RM_LAYER;
	struct csinn_pad_params *line_11_param = csinn_alloc_params(sizeof(struct csinn_pad_params), sess);
	line_11_param->pad_value = 0.0;
	line_11_param->pad_mode = CSINN_PAD_CONSTANT;
	int pad_before[5] = {0, 0, 0, 1, 1};
	line_11_param->pad_before = pad_before;
	int pad_after[5] = {0, 0, 0, 1, 1};
	line_11_param->pad_after = pad_after;
	struct csinn_tensor *value_in_0 = csinn_alloc_tensor(sess);
	value_in_0->dim[0] = 1;
	value_in_0->dim[1] = 10;
	value_in_0->dim[2] = 20;
	value_in_0->dim[3] = 30;
	value_in_0->dim[4] = 40;
	value_in_0->dim_count = 5;
	value_in_0->layout = CSINN_LAYOUT_NULL;
	value_in_0->is_const = 0;
	value_in_0->quant_channel = 1;
	value_in_0->dtype = CSINN_DTYPE_FLOAT32;
	value_in_0->data = malloc(1 * 10 * 20 * 30 * 40 * sizeof(float));
	struct csinn_tensor *value_in_0_pad = csinn_alloc_tensor(sess);
	value_in_0_pad->dim[0] = 1;
	value_in_0_pad->dim[1] = 10;
	value_in_0_pad->dim[2] = 20;
	value_in_0_pad->dim[3] = 32;
	value_in_0_pad->dim[4] = 42;
	value_in_0_pad->dim_count = 5;
	value_in_0_pad->layout = CSINN_LAYOUT_NULL;
	value_in_0_pad->is_const = 0;
	value_in_0_pad->quant_channel = 1;
	value_in_0_pad->dtype = CSINN_DTYPE_FLOAT32;
	value_in_0_pad->data = malloc(1 * 10 * 20 * 32 * 42 * sizeof(float));
	csinn_pad_init(value_in_0, value_in_0_pad, line_11_param);
	struct csinn_transpose_params *line_12_param = csinn_alloc_params(sizeof(struct csinn_transpose_params), sess);
	line_12_param->permute_num = 5;
	int permute[5] = {0, 1, 3, 4, 2};
	line_12_param->permute = permute;
	struct csinn_tensor *value_25_Pad = csinn_alloc_tensor(sess);
	value_25_Pad->dim[0] = 1;
	value_25_Pad->dim[1] = 10;
	value_25_Pad->dim[2] = 32;
	value_25_Pad->dim[3] = 42;
	value_25_Pad->dim[4] = 20;
	value_25_Pad->dim_count = 5;
	value_25_Pad->layout = CSINN_LAYOUT_NULL;
	value_25_Pad->is_const = 0;
	value_25_Pad->quant_channel = 1;
	value_25_Pad->dtype = CSINN_DTYPE_FLOAT32;
	value_25_Pad->data = malloc(1 * 10 * 32 * 42 * 20 * sizeof(float));
	csinn_transpose_init(value_in_0_pad, value_25_Pad, line_12_param);
	uint64_t start_time, end_time;
	start_time = shl_get_timespec();
	csinn_pad(value_in_0, value_in_0_pad, line_11_param);
	csinn_transpose(value_in_0_pad, value_25_Pad, line_12_param);
	end_time = shl_get_timespec();
	printf("Run graph execution time: %.5fms, FPS=%.2f\n", ((float)(end_time - start_time)) / 1000000, 1000000000.0 / ((float)(end_time - start_time)));
	return 0;
}
